---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: secureblue
description: Custom Secureblue image.
base-image: ghcr.io/secureblue/silverblue-nvidia-open-hardened
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: dnf
    repos:
      cleanup: true
    remove:
      packages:
        - fedora-bookmarks
        - gnome-classic-session
        - gnome-initial-Setup
        - gnome-shell-extension-apps-menu
        - gnome-shell-extension-launch-new-instance
        - gnome-shell-extension-places-menu
        - gnome-shell-extension-window-list
        - gnome-software
        - gnome-system-monitor
        # - gnome-tweaks # Upstream
        - httpd-filesystem
        - httpd-tools
        - malcontent-control
    install:
      install-weak-deps: false
      packages:
        # - adw-gtk3-theme # Upstream
        - android-tools
        - btop
        - btrfs-assistant
        - gnome-shell-extension-blur-my-shell
        - gnome-shell-extension-dash-to-dock
        - gnome-shell-extension-just-perfection
        - hplip
        - libcamera-gstreamer
        - libcamera-tools
        - libratbag-ratbagd
        - lshw
        - nvtop
        - podman-compose
        - powerline-fonts
        - smartmontools
        - solaar
        - solaar-udev
        - sushi
        - v4l-utils
        # - wireguard-tools # Upstream
  - type: gnome-extensions
    install:
      - Alphabetical App Grid
      - Burn My Windows
      - Color Picker
      - Compiz alike magic lamp effect
      - Emoji Copy
      - Gnome 4x UI Improvements
      - GNOME Fuzzy App Search
      - PiP on top
      - Tiling Shell
  - type: default-flatpaks
    notify: true
    system:
      install:
        - io.bassi.Amberol
        - com.belmoussaoui.Authenticator
        # - com.cassidyjames.butler # Butler - Home Assistant
        - org.gnome.Calculator
        - org.gnome.Snapshot # Camera
        # - hu.irl.cameractrls
        - es.danirod.Cartero
        - com.github.rafostar.Clapper
        - org.gnome.clocks
        - me.iepure.devtoolbox
        - org.gnome.baobab # Disk Usage Analyzer
        - com.github.wwmm.easyeffects
        - org.gnome.Epiphany # GNOME Web
        - com.mattjakeman.ExtensionManager
        - org.mozilla.firefox
        - org.gnome.Firmware
        - com.github.tchx84.Flatseal
        - org.gnome.font-viewer
        - de.haeckerfelix.Fragments
        - fr.handbrake.ghb
        - org.gnome.Loupe # Image Viewer
        - org.inkscape.Inkscape
        - re.sonny.Junction
        - org.kde.kdenlive
        - org.libreoffice.LibreOffice
        - org.gnome.Logs
        - io.missioncenter.MissionCenter
        - re.sonny.OhMySVG
        - org.gnome.Papers
        - com.github.PintaProject.Pinta
        - page.tesk.Refine
        - io.gitlab.adhami3310.Converter # Switcheroo
        # - org.gnome.Podcasts
        - org.gnome.World.Secrets
        - org.gnome.TextEditor
        # - me.iepure.Ticketbooth
        - io.github.flattool.Warehouse
        - com.vscodium.codium
        - org.gtk.Gtk3theme.adw-gtk3
        - org.gtk.Gtk3theme.adw-gtk3-dark
  - type: systemd
    system:
      enabled:
        - dconf-update.service
      masked:
        - rpm-ostree-countme.timer
  - type: files
    files:
      - source: system/etc
        destination: /etc
  - type: script
    scripts:
      - setup.sh
  - type: signing
