---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: secureblue
description: Custom Secureblue image.
base-image: ghcr.io/secureblue/silverblue-nvidia-open-hardened
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: dnf
    repos:
      cleanup: true
      files:
        - 1password.repo
      keys:
        - https://downloads.1password.com/linux/keys/1password.asc
      copr:
        - the4runner/firefox-dev
    optfix:
      - 1Password
      - firefox-dev
    remove:
      packages:
        - adw-gtk3-theme
        - fedora-bookmarks
        - gnome-classic-session
        - gnome-initial-Setup
        - gnome-shell-extension-apps-menu
        - gnome-shell-extension-launch-new-instance
        - gnome-shell-extension-places-menu
        - gnome-shell-extension-window-list
        - gnome-software
        - gnome-system-monitor
        - gnome-tweaks
        - httpd-filesystem
        - httpd-tools
        - malcontent-control
    install:
      install-weak-deps: false
      packages:
        - 1password
        - adobe-source-code-pro-fonts
        - android-tools
        - btop
        - ddcutil
        - docker-compose
        - firefox-dev
        - gnome-shell-extension-blur-my-shell
        - gnome-shell-extension-dash-to-dock
        - gnome-shell-extension-just-perfection
        - hplip
        - libcamera-gstreamer
        - libcamera-tools
        - libratbag-ratbagd
        - lshw
        - nvim
        - nvtop
        - p7zip-plugins
        - podman-compose
        - powerline-fonts
        - smartmontools
        - solaar
        - solaar-udev
        - tmux
        - v4l-utils
  - type: gnome-extensions
    install:
      - Alphabetical App Grid
      - Burn My Windows
      - Bluetooth Battery Meter
      - Compiz alike magic lamp effect
      - Emoji Copy
      - Gnome 4x UI Improvements
      - GNOME Fuzzy App Search
      - PiP on top
      - Search Light
      - Tiling Shell
  - type: default-flatpaks
    notify: true
    system:
      install:
        - io.bassi.Amberol
        - org.gnome.Calculator
        - org.gnome.Snapshot
        - hu.irl.cameractrls
        - es.danirod.Cartero
        - com.github.rafostar.Clapper
        - org.gnome.clocks
        - me.iepure.devtoolbox
        - org.gnome.baobab
        - com.github.wwmm.easyeffects
        - org.gnome.Epiphany
        - com.mattjakeman.ExtensionManager
        - com.github.tchx84.Flatseal
        - org.gnome.font-viewer
        - fr.handbrake.ghb
        - org.gnome.Loupe
        - org.inkscape.Inkscape
        - re.sonny.Junction
        - org.kde.kdenlive
        - org.libreoffice.LibreOffice
        - org.gnome.Logs
        - io.missioncenter.MissionCenter
        - org.gnome.NautilusPreviewer
        - com.obsproject.Studio
        - org.gnome.Papers
        - com.github.PintaProject.Pinta
        - org.gnome.Podcasts
        - org.gnome.TextEditor
        - io.github.flattool.Warehouse
  - type: systemd
    system:
      enabled:
        - adw-gtk3-update.service
        - dconf-update.service
        - dirty-centisecs.service
        - memory-tweaks-gidro.service
      masked:
        - rpm-ostree-countme.timer
  - type: script
    scripts:
      - setup.sh
  - type: gschema-overrides
  - type: signing
