- 1.1.14
- _NAME: MX Master 3 Wireless Mouse
  _absent:
    [
      hi-res-scroll,
      lowres-scroll-mode,
      onboard_profiles,
      report_rate,
      report_rate_extended,
      pointer_speed,
      dpi_extended,
      speed-change,
      backlight,
      backlight_level,
      backlight_duration_hands_out,
      backlight_duration_hands_in,
      backlight_duration_powered,
      backlight-timed,
      led_control,
      led_zone_,
      rgb_control,
      rgb_zone_,
      brightness_control,
      per-key-lighting,
      fn-swap,
      persistent-remappable-keys,
      disable-keyboard-keys,
      crown-smooth,
      divert-crown,
      divert-gkeys,
      m-key-leds,
      mr-key-led,
      multiplatform,
      gesture2-gestures,
      gesture2-divert,
      gesture2-params,
      sidetone,
      equalizer,
      adc_power_management,
    ]
  _battery: 4096
  _modelId: B02340820000
  _sensitive: { divert-keys: true, dpi: false, reprogrammable-keys: true }
  _serial: 30850AE0
  _unitId: 30850AE0
  _wpid: "4082"
  change-host: null
  divert-keys: { 82: 0, 83: 0, 86: 0, 195: 2, 196: 0 }
  dpi: 1800
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  reprogrammable-keys:
    { 80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 195, 196: 196 }
  scroll-ratchet: 1
  smart-shift: 1
  thumb-scroll-invert: false
  thumb-scroll-mode: false
- _NAME: G502 X PLUS
  _absent:
    [
      hi-res-scroll,
      lowres-scroll-mode,
      scroll-ratchet,
      smart-shift,
      thumb-scroll-invert,
      thumb-scroll-mode,
      report_rate_extended,
      pointer_speed,
      dpi_extended,
      speed-change,
      backlight,
      backlight_level,
      backlight_duration_hands_out,
      backlight_duration_hands_in,
      backlight_duration_powered,
      backlight-timed,
      led_control,
      led_zone_,
      brightness_control,
      fn-swap,
      reprogrammable-keys,
      persistent-remappable-keys,
      divert-keys,
      disable-keyboard-keys,
      crown-smooth,
      divert-crown,
      divert-gkeys,
      m-key-leds,
      mr-key-led,
      multiplatform,
      change-host,
      gesture2-gestures,
      gesture2-divert,
      gesture2-params,
      sidetone,
      equalizer,
      adc_power_management,
    ]
  _battery: 4100
  _modelId: 4099C0950000
  _sensitive:
    {
      hires-scroll-mode: ignore,
      hires-smooth-invert: ignore,
      hires-smooth-resolution: ignore,
    }
  _serial: 11E9E153
  _unitId: 11E9E153
  _wpid: "4099"
  dpi: 1200
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  onboard_profiles: 2
  per-key-lighting: { 1: -1, 2: -1, 3: -1, 4: -1, 5: -1, 6: -1, 7: -1, 8: -1 }
  report_rate: 2
  rgb_control: 0
